name: GitHub Actions Demo
run-name: ${{ github.actor }} is merging out GitHub Actions 🚀
on:
  pull_request:
    branches: 
      - main
    types: [closed]

jobs:
  my-action:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo "merge test"
